### ISSUE TITLE
[BUG] PyPI Binary incompatibility on numpy array

### ISSUE THREAD

**Issue by awickert** [Loop3D/LoopStructural#58]
`LoopStructural` fails on `import LoopStructural` with the message:

`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`

`LoopStructural-1.0.86` was installed for Python 3.8.5 on Ubuntu 20.04 with `pip3 install LoopStructural`. I note that the current PyPI version is 1.0.87; I will wait a moment and see if pip updates with this new release.

**Comment by awickert** [comment]
After trying for a little while to install v1.0.87, I found that it has not been built for Python 3.8; see https://pypi.org/project/LoopStructural/1.0.87/#files.

**Comment by lachlangrose** [comment]
Hi Andrew,

I just pushed a new release 1.0.88 which should force the build to be run for all platforms. The error with the numpy arrays is due to compiling with a different version of NumPy to that which is used on the system and Cython complains. I can't find a work around, so I have added a requirement for numpy 1.18 for loopstructural. I'll hopefully remove cython code from numpy in the future to remove this dependency.

Thanks for the feedback.

Lachlan

**Comment by awickert** [comment]
This numpy library version makes sense to me; thank you for this.

However, it seems that the pip install is still not being built for Python 3.8: https://pypi.org/project/LoopStructural/#files

**Comment by lachlangrose** [comment]
Try again, 1.0.89 I added a typo in the build script for 3.8 and 3.9 since adding macos in, they all appear on pypi now.

**Comment by awickert** [comment]
Import successful with 1.0.89. I will now start running the tests and possibly open future issues. Closing this as solved.
